resources:
  - name: git-repo
    type: git
    source:
      uri: <your-git-repo-url> # e.g., https://github.com/yourusername/my-app.git
      branch: main
 
jobs:
  - name: test
    plan:
      - get: git-repo
        trigger: true
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: gradle, tag: jdk17 }
          inputs:
            - name: git-repo
          run:
            path: sh
            args:
              - -c
              - |
                cd git-repo
                ./gradlew test