resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/sachinshelkesm/demo.git
      branch: main

jobs:
  - name: build-and-test
    plan:
      - get: git-repo
        trigger: true
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: gradle, tag: latest }
          inputs:
            - name: git-repo
          run:
            path: sh
            args:
              - -c
              - |
                cd git-repo
                ./gradlew test